"""time pressure band

Revision ID: 01c93f31606a
Revises: f653d829613b
Create Date: 2026-08-22 15:19:15.106702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c93f31606a'
down_revision = 'f653d829613b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_analyses', sa.Column('time_pressure_band', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'time_pressure_band')
    # ### end Alembic commands ###
