"""initial schema

Revision ID: 86eaa5bca789
Revises: 
Create Date: 2026-08-22 07:14:15.940028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86eaa5bca789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chess_com_uuid', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('time_control', sa.String(length=32), nullable=False),
    sa.Column('time_class', sa.String(length=32), nullable=False),
    sa.Column('rules', sa.String(length=32), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('eco', sa.String(length=255), nullable=True),
    sa.Column('opening_name', sa.String(length=128), nullable=True),
    sa.Column('white_username', sa.String(length=64), nullable=False),
    sa.Column('white_rating', sa.Integer(), nullable=False),
    sa.Column('black_username', sa.String(length=64), nullable=False),
    sa.Column('black_rating', sa.Integer(), nullable=False),
    sa.Column('white_result', sa.String(length=32), nullable=False),
    sa.Column('black_result', sa.String(length=32), nullable=False),
    sa.Column('user_color', sa.String(length=8), nullable=False),
    sa.Column('user_result', sa.String(length=8), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chess_com_uuid', name='uq_games_chess_com_uuid')
    )
    op.create_index(op.f('ix_games_analyzed'), 'games', ['analyzed'], unique=False)
    op.create_index(op.f('ix_games_chess_com_uuid'), 'games', ['chess_com_uuid'], unique=False)
    op.create_index(op.f('ix_games_end_time'), 'games', ['end_time'], unique=False)
    op.create_index(op.f('ix_games_time_class'), 'games', ['time_class'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('games_fetched', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'year_month', name='uq_sync_state_username_month')
    )
    op.create_index(op.f('ix_sync_state_username'), 'sync_state', ['username'], unique=False)
    op.create_table('move_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('side_to_move', sa.String(length=8), nullable=False),
    sa.Column('fen_before', sa.String(length=96), nullable=False),
    sa.Column('san', sa.String(length=16), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('eval_before_cp', sa.Integer(), nullable=True),
    sa.Column('eval_before_mate', sa.Integer(), nullable=True),
    sa.Column('eval_after_cp', sa.Integer(), nullable=True),
    sa.Column('eval_after_mate', sa.Integer(), nullable=True),
    sa.Column('best_move_uci', sa.String(length=8), nullable=True),
    sa.Column('best_move_san', sa.String(length=16), nullable=True),
    sa.Column('centipawn_loss', sa.Integer(), nullable=False),
    sa.Column('move_rank', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('game_phase', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_move_analyses_game_ply')
    )
    op.create_index(op.f('ix_move_analyses_game_id'), 'move_analyses', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_analyses_game_id'), table_name='move_analyses')
    op.drop_table('move_analyses')
    op.drop_index(op.f('ix_sync_state_username'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_games_time_class'), table_name='games')
    op.drop_index(op.f('ix_games_end_time'), table_name='games')
    op.drop_index(op.f('ix_games_chess_com_uuid'), table_name='games')
    op.drop_index(op.f('ix_games_analyzed'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
