"""drill tracking and coaching reports

Revision ID: 7b44c09caba7
Revises: 86eaa5bca789
Create Date: 2026-08-22 07:45:56.662020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b44c09caba7'
down_revision = '86eaa5bca789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('games_analyzed_count', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths_json', sa.Text(), nullable=False),
    sa.Column('weaknesses_json', sa.Text(), nullable=False),
    sa.Column('focus_area', sa.Text(), nullable=False),
    sa.Column('opening_notes', sa.Text(), nullable=False),
    sa.Column('encouragement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('move_analyses', sa.Column('drilled_correct', sa.Boolean(), nullable=True))
    op.add_column('move_analyses', sa.Column('drilled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'drilled_at')
    op.drop_column('move_analyses', 'drilled_correct')
    op.drop_table('coaching_reports')
    # ### end Alembic commands ###
