"""blunder tags and clock times

Revision ID: f653d829613b
Revises: 7b44c09caba7
Create Date: 2026-08-22 09:03:53.113452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f653d829613b'
down_revision = '7b44c09caba7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_analyses', sa.Column('blunder_tag', sa.String(length=24), nullable=True))
    op.add_column('move_analyses', sa.Column('clock_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'clock_seconds')
    op.drop_column('move_analyses', 'blunder_tag')
    # ### end Alembic commands ###
